"""Auditable personal knowledge workspace primitives."""

from core.knowledge.datasets import (
    CorpusManifestEntry,
    EvalCase,
    EvalDatasetManifest,
    EvalPassage,
    VersionedKnowledgeDataset,
    load_versioned_dataset,
    validate_eval_dataset,
)
from core.knowledge.embeddings import (
    OpenAICompatibleEmbeddingConfig,
    OpenAICompatibleEmbeddingProvider,
)
from core.knowledge.eval_runner import (
    GateCalibration,
    GateObservation,
    calibrate_gate,
    compare_layered_reports,
    run_postgres_layered_eval,
    run_sqlite_layered_eval,
)
from core.knowledge.evolution import EvidenceLearning, EvidenceLearningCitation
from core.knowledge.goals import (
    LearningCapability,
    LearningGoal,
    LearningGoalDefinition,
    LearningGoalError,
)
from core.knowledge.graph import (
    KnowledgeGraphEdge,
    KnowledgeGraphError,
    KnowledgeGraphEvidence,
    KnowledgeGraphNeighborhood,
    KnowledgeGraphNode,
    KnowledgeGraphOverview,
    KnowledgeGraphRelationPath,
    KnowledgeGraphSnapshot,
    LocalKnowledgeGraph,
)
from core.knowledge.graph_analysis import (
    KnowledgeGoalAlignment,
    KnowledgeGraphAnalysis,
    KnowledgeGraphAnalysisError,
    KnowledgeGraphAnalysisSnapshot,
    KnowledgeGraphCommunity,
    KnowledgeGraphInsight,
    KnowledgeGraphNodeMetric,
    LocalKnowledgeGraphAnalyzer,
)
from core.knowledge.index_backend import KnowledgeIndexBackend
from core.knowledge.index_factory import build_knowledge_index
from core.knowledge.migration import (
    KnowledgeMigrationItem,
    KnowledgeMigrationPlan,
    KnowledgeMigrationResult,
    KnowledgeMigrationResultItem,
)
from core.knowledge.postgres_index import (
    POSTGRES_INDEX_SCHEMA_REVISION,
    PostgresKnowledgeIndex,
    PostgresKnowledgeIndexConfig,
)
from core.knowledge.relevance import (
    KnowledgeRelevancePolicy,
    KnowledgeRelevancePolicyError,
    load_relevance_policy,
)
from core.knowledge.retrieval import (
    HashingEmbeddingProvider,
    KnowledgeChunk,
    KnowledgeEvidence,
    KnowledgeIndexSummary,
    KnowledgeRetrievalBundle,
    KnowledgeRetrievalMode,
    KnowledgeSearchHit,
    assemble_retrieval_bundle,
)
from core.knowledge.store import (
    KnowledgeConflictError,
    KnowledgeEvent,
    KnowledgeEvidenceError,
    KnowledgePage,
    KnowledgePageDocument,
    KnowledgePageRevision,
    KnowledgePolicyDecision,
    KnowledgeProjectionError,
    KnowledgeProposal,
    KnowledgeSourceRoot,
    KnowledgeStore,
    KnowledgeSummary,
    LoadedKnowledgeSource,
    PreparedKnowledgeSource,
)
from core.knowledge.synthesis import WorkspaceSourceEvidence, WorkspaceSynthesis
from core.knowledge.understanding import (
    SourceSection,
    SourceUnderstanding,
    UnderstandingCitation,
)

__all__ = [
    "POSTGRES_INDEX_SCHEMA_REVISION",
    "CorpusManifestEntry",
    "EvalCase",
    "EvalDatasetManifest",
    "EvalPassage",
    "EvidenceLearning",
    "EvidenceLearningCitation",
    "GateCalibration",
    "GateObservation",
    "HashingEmbeddingProvider",
    "KnowledgeChunk",
    "KnowledgeConflictError",
    "KnowledgeEvent",
    "KnowledgeEvidence",
    "KnowledgeEvidenceError",
    "KnowledgeGoalAlignment",
    "KnowledgeGraphAnalysis",
    "KnowledgeGraphAnalysisError",
    "KnowledgeGraphAnalysisSnapshot",
    "KnowledgeGraphCommunity",
    "KnowledgeGraphEdge",
    "KnowledgeGraphError",
    "KnowledgeGraphEvidence",
    "KnowledgeGraphInsight",
    "KnowledgeGraphNeighborhood",
    "KnowledgeGraphNode",
    "KnowledgeGraphNodeMetric",
    "KnowledgeGraphOverview",
    "KnowledgeGraphRelationPath",
    "KnowledgeGraphSnapshot",
    "KnowledgeIndexBackend",
    "KnowledgeIndexSummary",
    "KnowledgeMigrationItem",
    "KnowledgeMigrationPlan",
    "KnowledgeMigrationResult",
    "KnowledgeMigrationResultItem",
    "KnowledgePage",
    "KnowledgePageDocument",
    "KnowledgePageRevision",
    "KnowledgePolicyDecision",
    "KnowledgeProjectionError",
    "KnowledgeProposal",
    "KnowledgeRelevancePolicy",
    "KnowledgeRelevancePolicyError",
    "KnowledgeRetrievalBundle",
    "KnowledgeRetrievalMode",
    "KnowledgeSearchHit",
    "KnowledgeSourceRoot",
    "KnowledgeStore",
    "KnowledgeSummary",
    "LearningCapability",
    "LearningGoal",
    "LearningGoalDefinition",
    "LearningGoalError",
    "LoadedKnowledgeSource",
    "LocalKnowledgeGraph",
    "LocalKnowledgeGraphAnalyzer",
    "OpenAICompatibleEmbeddingConfig",
    "OpenAICompatibleEmbeddingProvider",
    "PostgresKnowledgeIndex",
    "PostgresKnowledgeIndexConfig",
    "PreparedKnowledgeSource",
    "SourceSection",
    "SourceUnderstanding",
    "UnderstandingCitation",
    "VersionedKnowledgeDataset",
    "WorkspaceSourceEvidence",
    "WorkspaceSynthesis",
    "assemble_retrieval_bundle",
    "build_knowledge_index",
    "calibrate_gate",
    "compare_layered_reports",
    "load_relevance_policy",
    "load_versioned_dataset",
    "run_postgres_layered_eval",
    "run_sqlite_layered_eval",
    "validate_eval_dataset",
]
