"""Cross-session, evidence-backed learning projections."""

from core.learning.activation import (
    LearningActivationError,
    LearningActivationRecord,
    LearningActivationService,
    LearningActivationTurnContextBinding,
    LearningGoalRef,
)
from core.learning.mastery import (
    MASTERY_RUBRIC_REVISION,
    MasteryCapability,
    MasteryCapabilityProjection,
    MasteryEvidence,
    MasteryEvidenceInput,
    MasteryEvidenceKind,
    MasteryEvidenceResult,
    MasteryEvidenceStatus,
    MasteryGoalProjection,
    MasteryLedger,
    MasteryLedgerConflictError,
    MasteryLedgerNotFoundError,
)
from core.learning.task_repository import (
    LearningTaskConflictError,
    LearningTaskError,
    LearningTaskNotFoundError,
    LearningTaskRepository,
    LearningTaskService,
)
from core.learning.tasks import (
    FINANCIAL_EDUCATION_NOTICE,
    UNSET,
    LearningClarification,
    LearningClarificationQuestion,
    LearningLearnerProfile,
    LearningSourcePolicy,
    LearningTask,
    LearningTaskCreate,
    LearningTaskPatch,
    UnsetValue,
)

__all__ = [
    "FINANCIAL_EDUCATION_NOTICE",
    "MASTERY_RUBRIC_REVISION",
    "UNSET",
    "LearningActivationError",
    "LearningActivationRecord",
    "LearningActivationService",
    "LearningActivationTurnContextBinding",
    "LearningClarification",
    "LearningClarificationQuestion",
    "LearningGoalRef",
    "LearningLearnerProfile",
    "LearningSourcePolicy",
    "LearningTask",
    "LearningTaskConflictError",
    "LearningTaskCreate",
    "LearningTaskError",
    "LearningTaskNotFoundError",
    "LearningTaskPatch",
    "LearningTaskRepository",
    "LearningTaskService",
    "MasteryCapability",
    "MasteryCapabilityProjection",
    "MasteryEvidence",
    "MasteryEvidenceInput",
    "MasteryEvidenceKind",
    "MasteryEvidenceResult",
    "MasteryEvidenceStatus",
    "MasteryGoalProjection",
    "MasteryLedger",
    "MasteryLedgerConflictError",
    "MasteryLedgerNotFoundError",
    "UnsetValue",
]
